### PR TITLE
Restore functional tests

### PR DESCRIPTION
**Pull request by francois2metz**
Trying to restore functional tests.

### CODE REVIEW

**Comment by iFgR** [comment]
Thank you for your contributions. These functional tests you created drew a doubt that I had.

Can I add you to this project?

**Comment by francois2metz** [comment]
I. Sure you can, I would be happy to help.

**Comment by iFgR** [comment]
Thanks! I send you an invitation.

I added 2 more functional tests, but they failed. The curious thing is that when I perform each test alone, it passes successful

Can you see what I did wrong?

**Comment by iFgR** [comment]
The code is on https://github.com/iFgR/vue-shortkey/blob/francois2metz-update_readme/test/functional.test.js

**Comment by francois2metz** [comment]
I guess you need to trigger some `keyup` events to reset the `keyPressed` variable.

**Comment by francois2metz** [comment]
I have updated the branch `francois2metz-update_readme` to fix tests. See d2c220616a306b4548dcf84c350a2d4dde0c365d. Tell me what you think.

**Comment by iFgR** [comment]
It's running fine here! Great!!! Can you do a pull request?

**Comment by francois2metz** [comment]
Closed in favor of #20

**Pull request closed without merging**
