### PR TITLE
Fix v-shortkey.avoid.

### PR DESCRIPTION
**Pull request by francois2metz**
There was 2 bugs with `v-shortkey.avoid`

- `v-shortkey.avoid` was no used to filter events
- `unbind` avoided elements triggered an error

### CODE REVIEW

**Comment by iFgR** [comment]
Great job!!
I'm checking your pull request to mrege.
Thanks a lot!

**Comment by iFgR** [comment]
Hi!
I had to remove the tests because they were giving error in the creation of the document.
Can you take a look?

**Comment by francois2metz** [comment]
Hi, 

I'll look at it.

**Comment by francois2metz** [comment]
I cannot see any errors on circleci. Do you have a problem in local? Could you give some details?

**Pull request merged**
