### PR TITLE
Fix bind special characters

### PR DESCRIPTION
**Pull request by keivio**
<button v-shortkey.pushButton="['shift', '?']" @shortkey="theAction()">Open</button>

### CODE REVIEW

**Comment by francois2metz** [comment]
Hi @keivio. Thanks for your contribution. Could you please add a test to prevent any regressions in the future?

**Comment by keivio** [comment]
Hi @francois2metz, yes i'll do it soon as possible

**Comment by francois2metz** [comment]
Ok, tell me if you run into any problems.

**Comment by francois2metz** [comment]
Hi @keivio. Can you check on master. I believe your issue is now fixed.

**Comment by keivio** [comment]
It is, thanks

**Pull request closed without merging**
